language: ruby
cache: bundler
bundler_args: --without benchmarks tools
rvm:
  - ruby-head
  - 2.6
  - 2.5
  - 2.4
env:
  - "DRY_VALIDATION='~> 1.3.0'"
  - "DRY_VALIDATION='~> 1.2.0'"
  - "DRY_VALIDATION='~> 1.1.0'"
  - "DRY_VALIDATION='~> 1.0.0'"
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

# maybe move this to slack in a private channel
# notifications:
#   webhooks:
#     urls:
#       - https://webhooks.gitter.im/e/680e86d98056f2ae2fd7
#     on_success: change  # options: [always|never|change] default: always
#     on_failure: always  # options: [always|never|change] default: always
#     on_start: never     # options: [always|never|change] default: always
